version: 2
updates:
  - package-ecosystem: "terraform"
    directories: 
      - "/terraform"
      - "/terraform-backup"
      - "/terraform-cross-account"
      - "/terraform-dashboard"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
    open-pull-requests-limit: 100
  - package-ecosystem: "pip"
    directories: 
      - "/dynamo-migration-lambda/app"
      - "/ehr-hard-deletion-lambda"
      - "/generate-cost-report-lambda"
      - "/notification-lambda/alarm"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
  - package-ecosystem: 'npm'
    directory: '/key-rotation-and-generation'
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
  - package-ecosystem: "github-actions" 
    directory: "/" 
    schedule: 
      interval: "weekly" 
      timezone: "Europe/London" 
      time: "09:00"
