version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
    labels:
      - "terraform"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "terraform"
    directory: "/terraform-backup"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
    labels:
      - "terraform-backup"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "terraform"
    directory: "/terraform-cross-account"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
    labels:
      - "terraform-cross-account"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "terraform"
    directory: "/terraform-dashboard"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
    labels:
      - "terraform-dashboard"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
