version: 0.2

phases:

  pre_build:
    commands:
      - chmod a+x ./utils/*
      - eval $(./utils/aws-cli-assumerole.sh -r $ASSUME_ROLE_NAME)
      - export TF_WARN_OUTPUT_ERRORS=true
  build:
    commands:
      - terraform init
      - terraform apply -auto-approve -var-file="terraform.tfvars"
