#!/bin/bash

set -Eeo pipefail

export AWS_DEFAULT_REGION=eu-west-2
NHS_SERVICE=deductions-infra

if [ -z "${DNS_IMAGE_TAG}" ]; then
  DNS_IMAGE_TAG="${GO_DEPENDENCY_LABEL_DOCKER_DNS_IMAGES}"
fi

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function tf_plan {
  check_env
  operation=$1
  certs=$2

  if [ -z "${DNS_IMAGE_TAG}" ]; then
    echo "DNS image tag has to be set"
    exit 1
  fi

  TARGET=""

  if [[ "${certs}" == "true" ]]; then
    TARGET="-target=module.deductions-private.aws_acm_certificate.mq-admin-cert -target=module.deductions-private.aws_acm_certificate.gp2gp-adaptor-cert"
  fi

  terraform init -backend-config key=${NHS_SERVICE}-${NHS_ENVIRONMENT}/terraform.tfstate
  terraform get # modules
  if [[ "${operation}" == "create" ]]; then
    terraform plan -var unbound_image_version=${DNS_IMAGE_TAG} -var-file=${NHS_ENVIRONMENT}.tfvars $TARGET -out="nhs_deployment.tfplan"
  elif [[ "${operation}" == "destroy" ]]; then
    terraform plan -var unbound_image_version=${DNS_IMAGE_TAG} -var-file=${NHS_ENVIRONMENT}.tfvars -out="nhs_deployment.tfplan" -destroy
  else
    echo "Unknown operation (should be create or destroy), got: ${operation}"
    exit 1
  fi
}

function tf_apply {
  check_env
  terraform init -reconfigure -backend-config key=${NHS_SERVICE}-${NHS_ENVIRONMENT}/terraform.tfstate
  terraform get # modules
  terraform apply nhs_deployment.tfplan
  terraform output -json > tf-out.json
}

function setup_vpn_ca {
  if [[ ! -d "easy-rsa" ]]; then
    git clone https://github.com/OpenVPN/easy-rsa.git
  fi
  cd easy-rsa/easyrsa3
  echo yes | ./easyrsa init-pki
  cd pki
  echo "$(get_aws_value "/repo/user-input/vpn-ca-crt")" > ca.crt
  echo "$(get_aws_value "/repo/user-input/vpn-ca-key")" > private/ca.key
  echo "$(get_aws_value "/repo/user-input/vpn-ca-serial")" > serial
  touch index.txt
  touch index.txt.attr
  mkdir -p certs_by_serial
  mkdir -p issued
  cd ..
}

function generate_vpn_ca {
  if [[ ! -d "easy-rsa" ]]; then
    git clone https://github.com/OpenVPN/easy-rsa.git
  fi
  cd easy-rsa/easyrsa3
  ./easyrsa init-pki
  EASYRSA_BATCH=true EASYRSA_REQ_CN="vpn.patient-deductions.nhs.uk" ./easyrsa build-ca nopass
  create_secret_ssm_param "/repo/user-input/vpn-ca-crt" "$(cat pki/ca.crt)"
  create_secret_ssm_param "/repo/user-input/vpn-ca-key" "$(cat pki/private/ca.key)"
  create_secret_ssm_param "/repo/user-input/vpn-ca-serial" "$(cat pki/serial)"
}

function generate_vpn_server_crt {
  check_env
  crt_id="${NHS_ENVIRONMENT}.vpn.patient-deductions.nhs.uk"
  existing_crt="$(aws acm list-certificates | jq -r --arg crt_id "$crt_id" '.CertificateSummaryList[] | select(.DomainName==$crt_id)')"
  if [[ -z $existing_crt ]]; then
    setup_vpn_ca
    ./easyrsa build-server-full $crt_id nopass

    aws acm import-certificate --certificate fileb://pki/issued/$crt_id.crt --private-key fileb://pki/private/$crt_id.key --certificate-chain fileb://pki/ca.crt
  else
    echo "Server certificate $crt_id already exists"
  fi
}

function generate_vpn_client_crt {
  check_env
  if [[ -z $1 ]]; then
    echo "Username required"
    exit 1
  fi
  username="$1"
  crt_id="$username.vpn.patient-deductions.nhs.uk"

  setup_vpn_ca
  if [[ ! -f pki/private/$crt_id.key ]]; then
    echo "Client key file not present. Generating now."
    ./easyrsa build-client-full $crt_id nopass
  fi

  client_crt="$(cat pki/issued/$crt_id.crt)"
  client_key="$(cat pki/private/$crt_id.key)"

  client_vpn_endpoint_id=$(get_aws_value "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-infra/client-vpn-endpoint-id")
  config="$(aws ec2 export-client-vpn-client-configuration --client-vpn-endpoint-id $client_vpn_endpoint_id | jq -r ".ClientConfiguration")"

  cd ../..
  dirname="client-config"
  mkdir -p $dirname
  cd $dirname
  filename="${NHS_ENVIRONMENT}.$username.ovpn"

  echo "$config" > $filename
  echo -e "<cert>\n$client_crt\n</cert>\n" >> $filename
  echo -e "<key>\n$client_key\n</key>\n" >> $filename

  echo "$username VPN client configuration file created in $dirname directory"
}

function create_secret_ssm_param {
  secret_id="$1"
  value="$2"
  set +e
  aws ssm get-parameter --region $AWS_DEFAULT_REGION --name $secret_id | jq -r ".Parameter.Value" > /dev/null
  if [[ $? == 0 ]]; then
    echo "Secret at $secret_id already exists"
  else
    set -e
    echo "Secret does not exists. Creating $secret_id"
    aws ssm put-parameter \
     --region $AWS_DEFAULT_REGION \
     --name $secret_id \
     --type SecureString \
     --overwrite \
     --value "$value"
  fi
}

function generate_secret_ssm_param {
  value=$(openssl rand -base64 24  | tr -d "/@\'+")
  create_secret_ssm_param $1 $value
}

function generate_username_ssm_param {
  value=$(< /dev/urandom tr -dc a-z | head -c12)
  create_secret_ssm_param "$1" "$value"
}

function create_ssm_param {
  value_id="$1"
  value="$2"
  set +e
  aws ssm get-parameter --region $AWS_DEFAULT_REGION --name $value_id | jq -r ".Parameter.Value"
  if [[ $? == 0 ]]; then
    echo "Value at $value_id already exists"
  else
    set -e
    echo "Value does not exists. Creating $value_id"
    aws ssm put-parameter \
     --region $AWS_DEFAULT_REGION \
     --name $value_id \
     --type String \
     --overwrite \
     --value "$value"
  fi
}

function get_aws_value {
  secret_id=$1
  json=$(aws ssm get-parameter --with-decryption --region $AWS_DEFAULT_REGION --name $secret_id)
  if [ $? != 0 ]; then
    >&2 echo "Failed to obtain SSM value: $secret_id"
    exit 5
  fi
  echo $json | jq -r ".Parameter.Value"
}

function generate_deductions_vpn_ssh_key {
  generate_ssh_key "/repo/user-input/ssh-id-rsa" "modules/ssh"
}

function generate_opentest_ssh_key {
  generate_ssh_key "/repo/user-input/opentest-ssh-id-rsa" "modules/mhs/cluster-network/opentest/ssh"
}

function generate_dns_ssh_key {
  generate_ssh_key "/repo/user-input/dns-ssh-id-rsa" "modules/mhs/cluster-network/dns/ssh"
}

function generate_ssh_key {
  secret_id=$1
  ssh_directory=$2
  mkdir -p ${ssh_directory}/
  if [[ ! -f "${ssh_directory}/id_rsa" ]]; then
    #TODO check aws authentication
    set +e
    id_rsa=$(aws ssm get-parameter --with-decryption --region $AWS_DEFAULT_REGION --name $secret_id | jq -r ".Parameter.Value")
    if [[ $? == 0 ]]; then
      echo "$id_rsa" > ${ssh_directory}/id_rsa
    else
      set -e
      ssh-keygen -f "${ssh_directory}/id_rsa" -q -N ""
    fi
    set -e
  fi
  chmod 0600 ${ssh_directory}/id_rsa
  ssh-keygen -y -f "${ssh_directory}/id_rsa" > "${ssh_directory}/id_rsa.pub"
  aws ssm put-parameter \
   --region $AWS_DEFAULT_REGION \
   --name $secret_id \
   --type SecureString \
   --overwrite \
   --value "`cat ${ssh_directory}/id_rsa`"
}

command="$1"
case "${command}" in
  _ssh_key)
      check_env
      generate_deductions_vpn_ssh_key
      generate_opentest_ssh_key
      generate_dns_ssh_key
      ;;
  ssh_key)
      dojo "./tasks _ssh_key"
      ;;
  _tf)
      check_env
      terraform init -backend-config key=${NHS_SERVICE}-${NHS_ENVIRONMENT}/terraform.tfstate
      bash
      ;;
  tf)
      dojo "./tasks _tf"
      ;;
  _tf_plan)
      ./tasks _ssh_key
      tf_plan "$2"
      ;;
  tf_plan)
      check_env
      dojo "./tasks _tf_plan $2"
      ;;
  _tf_plan_certs)
      tf_plan "$2" true
      ;;
  tf_plan_certs)
      check_env
      dojo "./tasks _tf_plan_certs $2"
      ;;
  _tf_apply)
      ./tasks _ssh_key
      tf_apply
      ;;
  tf_apply)
      check_env
      dojo "./tasks _tf_apply"
      ;;
  _wait_for_dns)
      check_env
      cluster_name=$2
      if [ -z $cluster_name ]; then
        echo "Please specify cluster name to verify"
      fi
      AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq -r .Account)
      DNS_SERVER_1=$(get_aws_value "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-infra/${cluster_name}-dns-ip-0")
      DNS_SERVER_1=$(echo "${DNS_SERVER_1}" | awk -F "," '{print $1}')
      DNS_SERVER_2=$(get_aws_value "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-infra/${cluster_name}-dns-ip-1")
      DNS_SERVER_2=$(echo "${DNS_SERVER_2}" | awk -F "," '{print $1}')
      echo "Waiting for DNS servers ${DNS_SERVER_1} and ${DNS_SERVER_2} to be ready"

      rm -f ./retry
      curl https://raw.githubusercontent.com/kadwanev/retry/master/retry -o ./retry
      chmod +x retry

      SLEEP_TIME=1
      DIG_TIMEOUT=1
      TRIES=60
      ./retry -v --tries=$TRIES --sleep=$SLEEP_TIME "1>&2 dig +timeout=$DIG_TIMEOUT redhat.com @${DNS_SERVER_1} & dig +timeout=$DIG_TIMEOUT redhat.com @${DNS_SERVER_1} | grep 'Got answer'"
      ./retry -v --tries=$TRIES --sleep=$SLEEP_TIME "1>&2 dig +timeout=$DIG_TIMEOUT redhat.com @${DNS_SERVER_2} & dig +timeout=$DIG_TIMEOUT redhat.com @${DNS_SERVER_2} | grep 'Got answer'"

      if [ "${NHS_ENVIRONMENT}" == "test" ]; then
        echo "Querying for private domain on HSCN network: nww.int.spine2.ncrs.nhs.uk"
        dig nww.int.spine2.ncrs.nhs.uk @${DNS_SERVER_1} | grep 'Got answer'
        dig nww.int.spine2.ncrs.nhs.uk @${DNS_SERVER_2} | grep 'Got answer'
        echo "OK. Received reply for an HSCN domain"
      fi
      ;;
  wait_for_dns)
      dojo "./tasks _wait_for_dns $2"
      ;;
  _create_secrets)
      generate_username_ssm_param "/repo/${NHS_ENVIRONMENT}/user-input/gp-to-repo-db-username"
      generate_secret_ssm_param "/repo/${NHS_ENVIRONMENT}/user-input/gp-to-repo-db-password"
      generate_username_ssm_param "/repo/${NHS_ENVIRONMENT}/user-input/repo-to-gp-db-username"
      generate_secret_ssm_param "/repo/${NHS_ENVIRONMENT}/user-input/repo-to-gp-db-password"
      generate_username_ssm_param "/repo/${NHS_ENVIRONMENT}/user-input/mq-admin-username"
      generate_secret_ssm_param "/repo/${NHS_ENVIRONMENT}/user-input/mq-admin-password"
      generate_username_ssm_param "/repo/${NHS_ENVIRONMENT}/user-input/mq-app-username"
      generate_secret_ssm_param "/repo/${NHS_ENVIRONMENT}/user-input/mq-app-password"
      ;;
  create_secrets)
      # Needs to run only once, when adding new environment
      check_env
      dojo "./tasks _create_secrets"
      ;;
  _generate_vpn_ca)
      generate_vpn_ca
      ;;
  generate_vpn_ca)
      dojo "./tasks _generate_vpn_ca"
      ;;
  _generate_vpn_server_crt)
      generate_vpn_server_crt
      ;;
  generate_vpn_server_crt)
      dojo "./tasks _generate_vpn_server_crt"
      ;;
  _generate_vpn_client_crt)
      generate_vpn_client_crt "$2"
      ;;
  generate_vpn_client_crt)
      dojo "./tasks _generate_vpn_client_crt $2"
      ;;
  _detect_active_mq)
      MQ_ENDPOINT_1=$(get_aws_value "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-infra/amqp-endpoint-0")
      MQ_ENDPOINT_2=$(get_aws_value "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-infra/amqp-endpoint-1")
      MQ_HOST_1=$(echo $MQ_ENDPOINT_1 | sed 's#amqp+ssl://##' | sed 's#:5671##')
      MQ_HOST_2=$(echo $MQ_ENDPOINT_2 | sed 's#amqp+ssl://##' | sed 's#:5671##')
      if nc -zvw3 $MQ_HOST_1 5671; then
        MQ_ENDPOINT_ACTIVE=$MQ_ENDPOINT_1
      elif nc -zvw3 $MQ_HOST_2 5671; then
        MQ_ENDPOINT_ACTIVE=$MQ_ENDPOINT_2
      else
        echo 'No MQ endpoint is reachable'
        exit 3;
      fi
      aws ssm put-parameter \
       --region "${AWS_DEFAULT_REGION}" \
       --name "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-infra/amqp-endpoint-active" \
       --type String \
       --overwrite \
       --value "$MQ_ENDPOINT_ACTIVE"
      echo "Stored active MQ endpoint at /repo/${NHS_ENVIRONMENT}/output/prm-deductions-infra/amqp-endpoint-active"
      ;;
  detect_active_mq)
      check_env
      dojo "./tasks _detect_active_mq"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
