format_version: 4
pipelines:
  "prm-deductions-api-key-rotation-and-generation":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - dev_keys:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: dev
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks test_keys
      - test_keys:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: test
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks test_keys
