format_version: 4
pipelines:
  "prm-deductions-api-key-rotation-and-generation":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        whitelist:
          - key-rotation-and-generation/**/*.*
          - gocd/keys.gocd.yml
    stages:
      - unit_tests:
          clean_workspace: true
          jobs:
            test_keys:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_keys
      - dev_env:
          clean_workspace: true
          jobs:
            generate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: dev
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks generate_keys
            rotate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: dev
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks rotate_keys
      - test_env:
          clean_workspace: true
          jobs:
            generate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: test
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks generate_keys
            rotate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: test
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks rotate_keys