format_version: 4
common:
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks create_secrets
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks generate_vpn_server_crt
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan_certs create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply_certs
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply

pipelines:
  "prm-deductions-infra-cross-account":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - key-rotation-and-generation/**/*.*
    stages:
      - deploy_ci:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: ci
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_plan_cross_account create
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_apply_cross_account
      - deploy_dev:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: dev
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_plan_cross_account create
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_apply_cross_account

      - deploy_test:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: test
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_plan_cross_account create
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_apply_cross_account

      - deploy_pre_prod:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: pre-prod
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_plan_cross_account create
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_apply_cross_account

      - deploy_prod:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: prod
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_plan_cross_account create
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_apply_cross_account

  "prm-deductions-infra":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - key-rotation-and-generation/**/*.*
    stages:
      - deploy_dev:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: dev
          jobs:
            apply: *deploy_job
      - deploy_test:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: test
          jobs:
            apply: *deploy_job
      - deploy_pre_prod:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: pre-prod
          jobs:
            apply: *deploy_job
      - plan_prod:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: prod
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: terraform/tf-out.json
                - build:
                    source: deployment.tfplan
                - build:
                    source: certs_deployment.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks create_secrets
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks generate_vpn_server_crt
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks tf_plan_certs create
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks tf_plan create
      - deploy_prod:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: prod
          jobs:
            deploy:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: terraform/tf-out.json
                    is_file: yes
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: certs_deployment.tfplan
                    is_file: yes
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: deployment.tfplan
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks tf_apply_certs
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks tf_apply
