format_version: 4
common:
  apply_job: &apply_job
    resources:
      - docker
    artifacts:
      - build:
          source: tf-out.json
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks create_secrets
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks generate_vpn_server_crt
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply

pipelines:
  "prm-deductions-infra":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - deploy_dev:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: dev
          jobs:
            apply: *apply_job
      - check_dev:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: dev
          jobs:
            test:
              resources:
                - dev
                - deductions-private # Agent runs in deductions private
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
            active_mq:
              resources:
                - dev
                - deductions-private # Agent runs in deductions private
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks detect_active_mq

      - deploy_test:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: test
          jobs:
            apply: *apply_job
      - check_test:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: test
          jobs:
            test:
              resources:
                - test
                - deductions-private # Agent runs in deductions private
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
            active_mq:
              resources:
                - test
                - deductions-private # Agent runs in deductions private
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks detect_active_mq
