format_version: 4
common:
  apply_job: &apply_job
    resources:
      - docker
    artifacts:
      - build:
          source: terraform/tf-out.json
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks create_secrets
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks generate_vpn_server_crt
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan_certs create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply

pipelines:
  "prm-deductions-infra-cross-account":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - key-rotation-and-generation/**/*.*
    stages:
      - deploy_ci:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: ci
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_plan_cross_account create
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_apply_cross_account
      - deploy_dev:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: dev
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_plan_cross_account create
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks tf_apply_cross_account

  "prm-deductions-infra":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - key-rotation-and-generation/**/*.*
      docker_dns_images:
        pipeline: mhs-dns-images
        stage: test
    stages:
      - promote_docker_image_dev:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: dev
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks promote_docker_image

      - deploy_dev:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: dev
          jobs:
            apply: *apply_job
      - wait_dns_dev:
          environment_variables:
            NHS_ENVIRONMENT: dev
          jobs:
            repo:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks wait_for_dns repo
            test_harness:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks wait_for_dns test-harness
      - promote_docker_image_test:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: test
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - deploy_test:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: test
          jobs:
            apply: *apply_job
      - wait_dns_test:
          environment_variables:
            NHS_ENVIRONMENT: test
          jobs:
            repo:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks wait_for_dns repo
