format_version: 4
pipelines:
  "prm-deductions-user-api-keys":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        whitelist:
          - key-rotation-and-generation/**/*.*
          - gocd/user-keys.gocd.yml
    stages:
      - unit_tests:
          clean_workspace: true
          jobs:
            test_keys:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_keys
      - dev_env:
          clean_workspace: true
          jobs:
            generate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: dev
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks generate_user_keys
            rotate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: dev
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks rotate_user_keys
      - test_env:
          clean_workspace: true
          jobs:
            generate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: test
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks generate_user_keys
            rotate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: test
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks rotate_user_keys
      - perf_env:
          clean_workspace: true
          jobs:
            generate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: perf
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks generate_user_keys
            rotate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: perf
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks rotate_user_keys
      - pre_prod_env:
          clean_workspace: true
          jobs:
            generate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: pre-prod
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks generate_user_keys
            rotate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: pre-prod
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks rotate_user_keys
      - prod_env:
          clean_workspace: true
          jobs:
            generate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: prod
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks generate_user_keys
            rotate_keys:
              resources:
                - docker
              environment_variables:
                NHS_ENVIRONMENT: prod
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks rotate_user_keys
