CUR_Output_Location: s3://${ENVIRONMENT}-cost-and-usage/reports/aws-cost-report/manual-test-results/
CUR_DB: >-
  "repo-aws-cost"."aws_cost_report"
CUR_Report_Name: ${ENVIRONMENT}_cost_and_usage_report.xlsx
Query_String_List:
  - ORIGINAL_QUERY: SELECT  product_product_name AS ServiceName, ROUND (SUM (pricing_public_on_demand_cost), 3) as Cost FROM CUR_DB
      WHERE (resource_tags_user_created_by like '%prm-deductions-ehr-repository%'
      OR resource_tags_user_created_by like '%end-of-transfer-service%'
      OR resource_tags_user_created_by like '%prm-deductions-nems-event-processor%'
      OR resource_tags_user_created_by like '%prm-deductions-gp-to-repo%'
      OR resource_tags_user_created_by like '%suspension-service%'
      OR resource_tags_user_created_by like '%prm-deductions-infra%'
      OR resource_tags_user_created_by like '%prm-deductions-gp2gp-messenger%'
      OR resource_tags_user_created_by like '%prm-deductions-mesh-forwarder%'
      OR resource_tags_user_created_by like '%prm-repo-re-registration-service%'
      OR resource_tags_user_created_by like '%prm-mhs-infra%'
      OR resource_tags_user_created_by like '%prm-deductions-support-infra%'
      OR resource_tags_user_created_by like '%prm-deductions-repo-to-gp%')
      GROUP BY product_product_name
      ORDER BY Cost DESC;